add favorite movies page
foxsheldin/my-favorite-movies-front pull request #2
Opened 2023-03-14 13:30 UTC by foxsheldin

2023-03-16 10:49 UTC, Isidora25 requested changes
после того как закроешь этот ПР, тебе нужно будет для локалей прикрутить i18n

2023-03-16 10:49 UTC, Isidora25 commented on src/api/movieAPI.ts
> +      const { favoriteGenres }: any = JSON.parse(
избавься от any

2023-03-16 10:49 UTC, Isidora25 commented on src/api/movieAPI.ts
> +      };
в react проектах принято использовать camelCase

2023-03-16 10:49 UTC, Isidora25 commented on src/api/movieAPI.ts
> +      )[0];
для чего здесь filter, если можно find использовать?

2023-03-16 10:49 UTC, Isidora25 commented on src/components/FavoriteMovie/index.tsx
> +        ))
нечитаемый кусок 

1. вынеси в отдельный комопнент
2. по аналогии с лоадером сразу возвращай сообщение нет данных 
3. остальные условия делай в рендере 

так как у тебя только два варианта для отображения использование тернарника будет короче

2023-03-16 10:49 UTC, Isidora25 commented on src/components/FavoriteMovie/index.tsx
> +                </ToggleButtonGroup>
Вынеси в отдельный компонент, будет лучше читаться

2023-03-16 10:49 UTC, Isidora25 commented on src/components/FavoriteMovie/styles.ts
> +export const CustomizedDiv = styled("div")`
можно использовать и такую запись `styled.div`
она короче

2023-03-16 10:49 UTC, Isidora25 commented on src/components/GenreList/index.tsx
> +          selected={selectedGenres.includes(id as number)}
для чего здесь приведение?

2023-03-16 10:49 UTC, Isidora25 commented on src/store/genre/selectors.ts
> +) => selectGenreArrayEntities(state).filter((genre) => genre?.id === genreId);
для поиска уникального элемента в массиве отлично подходит find

2023-03-16 10:49 UTC, Isidora25 commented on src/components/Message/index.tsx
> +    <Typography variant="h5" component={"p"} align="center">
строковые пропсы передаются без фигурных скобок

2023-03-16 10:49 UTC, Isidora25 commented on src/components/MovieAction/index.tsx
> +        </Tooltip>
Выглядит как заявка на компонент 
вынеси и переиспользуй

2023-03-16 10:49 UTC, Isidora25 commented on src/components/MovieViewList/index.tsx
> +const MovieViewList = ({ data }: IMovieViewListProps) => {
лучше использовать более говорящие имена для пропсов и переменных
data, item - безликие 
movies, movie - сразу сделают все более понятным

2023-03-16 10:49 UTC, Isidora25 commented on src/components/MovieViewListItem/index.tsx
> +          height="112.5"
дробные значения для разных браузеров интерпретируется по-разному 
кто-то огруляет, кто-то нет 
избавься от этого заранее чтобы иметь более предссказуемый результат

2023-03-16 10:49 UTC, Isidora25 commented on src/components/MovieViewModuleItem/index.tsx
> +      />
Уже видела этот кусок кода, можно вынести в компонент

2023-03-16 10:49 UTC, Isidora25 commented on src/components/MovieViewModuleItem/index.tsx
> +      <CustomizedImage
для img еще принято добавлять аттрибут alt 
если картинка декоративная и не несет полезной инфы - то он пуст 
если она важна - то внутри текстовое описание

2023-03-16 10:49 UTC, Isidora25 commented on src/components/NavBar/index.tsx
> +  };
просто навигация? 
а юзера вообще выкидывает?

2023-03-16 10:49 UTC, Isidora25 commented on src/pages/PanelLayout/index.tsx
> +type Props = {};
если пропсов нет, то и тип не нужен

2023-03-16 10:49 UTC, Isidora25 commented on src/store/favoriteMovie/selectors.ts
> +  { movieId }: { movieId: number }
{ movieId: number } много где повторяется, вынеси в интрефейс и переиспользуй

2023-03-16 10:49 UTC, Isidora25 commented on src/store/favoriteMovie/thunks.ts
> +      response = await movieAPI.createFavoriteMovie(movieData as IMovieData);
почему ты везде используешь переопредление типов? 
1. если у тебя нет четкого описания типов для параметров функции - их нужно типизировать

таким переназначением ты рискуешь поймать ошибку  переназнача тип чему-то другому

2023-03-16 10:49 UTC, Isidora25 commented on src/store/favoriteMovie/types.ts
> +  total_results: number;
camelCase

2023-03-16 10:49 UTC, Isidora25 commented on .env.example
> +REACT_APP_MOVIE_DB_IMAGE_URL_ORIGINAL=https://image.tmdb.org/t/p/original
а почему это лежит в энвах? 
это же обычные константы

2023-03-16 10:49 UTC, Isidora25 commented on src/components/MovieViewModuleItem/index.tsx
> +        }
сделай хелпер функцию, которая будет возвращать готовый src

2023-03-16 10:49 UTC, Isidora25 commented on src/temp/backend-data.ts
> +    28, 12, 35, 80, 18, 10751, 27, 10402, 9648, 10749, 878, 10770, 53,
снова дикая смесь из разных кейсов

2023-03-17 10:27 UTC, Isidora25 requested changes

2023-03-17 10:27 UTC, Isidora25 commented on src/helpers/getPathImage.ts
> +  MOVIE_DB_IMAGE_URL_ORIGINAL + imageName;
Функции делают одно и то же, константу для урла тоже можно параметризировать, тем более начало у них одинаковое 
const BASE_IMAGE_URL  = `https://image.tmdb.org/t/p/`

getImagePath(imageSize: 'original' | 'w500', imageName: string)

2023-03-17 10:38 UTC, Isidora25 requested changes

2023-03-17 10:38 UTC, Isidora25 commented on src/store/index.ts
> +    filter: filterSlice.reducer,
Старайся пожалуйста не добавлять нового функционала в рамках исправления замечаний после ревью

2023-03-17 10:44 UTC, foxsheldin commented on src/store/index.ts
> +    filter: filterSlice.reducer,
Хорошо. Учту. В данном случае было логично вынести функционал с изменением вида просмотра списка фильмов для двух новых компонент в отдельный слайс. Видимо стоило оставить его в стейте компонента

2023-03-17 11:02 UTC, Isidora25 approved these changes

2023-03-17 13:51 UTC, reshetov requested changes

2023-03-17 13:51 UTC, reshetov commented on src/api/movieAPI.ts
> +  baseURL: "https://api.themoviedb.org/3/",
Перекинь это тоже в константы src/api/constants.ts чтобы все URL в одном месте хранились

2023-03-17 13:51 UTC, reshetov commented on src/api/movieAPI.ts
> +  getFavoriteMovieList() {
Не нужно хранить в базе favorite movies (это жрет дофига места да и данные протухнуть легко могут)
Лучше хранить ID от объектов и подгружать их при переходе на странице

2023-03-17 13:51 UTC, reshetov commented on src/api/movieAPI.ts
> +          favoriteMovies: [...result.favoriteMovies],
Как связаны данные по жанрам и фильмы? Может растащить их по разным ключам?

2023-03-17 13:51 UTC, reshetov commented on src/api/movieAPI.ts
> +          favoriteGenres: [...tempObject.favoriteGenres],
см. комент выше

2023-03-17 13:51 UTC, reshetov commented on src/api/movieAPI.ts
> +          favoriteGenres: [...tempObject.favoriteGenres],
см. комент выше

2023-03-17 13:51 UTC, reshetov commented on src/components/GenreList/styles.ts
> +export const CustomizedDiv = styled.div`
"Изменнный div" так себе название для стилевого компонента, не понятно какая именно у него роль и почему от должен быть изменен, лучше что-то вроде Wrapper, WrappedDiv или т.п. Облегчай жизнь другими разрабам, сейчас им придется лезть в стилевой файл чтобы понять зачем этот div

2023-03-17 13:51 UTC, reshetov commented on src/components/MovieViewListItem/index.tsx
> +        <img
У тебя в соседнем компоненте эта картинка перенесена в отдельный компонент, а чего тут оставил?

2023-03-20 09:55 UTC, reshetov approved these changes

2023-03-20 10:00 UTC, Isidora25 approved these changes

2023-03-20 10:00 UTC, merged