Add localization
foxsheldin/my-favorite-movies-front pull request #3
Opened 2023-03-21 09:36 UTC by foxsheldin

2023-03-21 11:08 UTC, Isidora25 requested changes

2023-03-21 11:08 UTC, Isidora25 commented on public/locales/en/favoriteMoviePage.json
> +{
файлы, которые не являются реакт компонентами лучше именовать в kebab-case

2023-03-21 11:21 UTC, Isidora25 approved these changes

2023-03-22 06:40 UTC, reshetov approved these changes

2023-03-22 06:57 UTC, merged