feat: add graphql and apollo client
foxsheldin/my-favorite-movies-front pull request #6
Opened 2023-05-31 11:12 UTC by foxsheldin

2023-05-31 13:22 UTC, Isidora25 reviewed
если еще не, советую поставить расширение для gql

2023-05-31 13:22 UTC, Isidora25 commented on src/api/graphql/mutations/deleteFavoriteMovie.ts
> +      isWatched
кажется, тут тоже можно использовать фрагмент?

2023-05-31 13:22 UTC, Isidora25 commented on src/api/graphql/mutations/signIn.ts
> +    signIn(data: $data)
а тут тебе никакие данные от сервера не нужны?

2023-05-31 13:22 UTC, Isidora25 commented on src/api/graphql/queries/getFavoriteGenresList.ts
> +    getFavoriteGenresList(userId: $userId)
тут тоже пустой респонс будет

2023-05-31 14:06 UTC, foxsheldin commented on src/api/graphql/mutations/signIn.ts
> +    signIn(data: $data)
На текущем этапе мутация возвращает id пользователя

2023-05-31 14:08 UTC, foxsheldin commented on src/api/graphql/queries/getFavoriteGenresList.ts
> +    getFavoriteGenresList(userId: $userId)
Здесь возвращается массив с идентификаторами

2023-05-31 14:26 UTC, Isidora25 approved these changes

2023-06-01 09:05 UTC, reshetov requested changes

2023-06-01 09:05 UTC, reshetov commented on src/api/graphql/mutations/createFavoriteMovie.ts
> +    $language: String
А зачем тут language? Если уж ты хочешь заморочится с языками - это нужно в настройки пользователя прописывать и работать с ними. Но тут можно просто забить на это и использовать default язык

2023-06-01 09:29 UTC, reshetov approved these changes

2023-06-01 09:29 UTC, merged