Server integration
foxsheldin/my-favorite-movies-front pull request #7
Opened 2023-06-08 07:24 UTC by foxsheldin

2023-06-15 06:54 UTC, Isidora25 approved these changes

2023-06-16 07:51 UTC, reshetov requested changes

2023-06-16 07:51 UTC, reshetov commented on src/api/graphql/hooks/mutations/useCreateFavoriteMovieMutation.ts
> +        userId: localStorage.getItem("DB_user_id") ?? "",
Сделай на беке метод заглушку пока у тебя JWT токенов нет и там проверяй, а тут не нужно

2023-07-07 07:27 UTC, reshetov requested changes

2023-07-07 07:27 UTC, reshetov commented on src/api/graphql/hooks/mutations/useUpdateWatchedMovieStatusMutation.ts
> +    status: boolean
Тут по идее можно без статуса обойтись (как у тебя сейчас с жанрами), если идет обновление - на беке фильм переключается в обратный статус

2023-07-07 07:27 UTC, reshetov commented on src/api/graphql/hooks/queries/useGetAllAvailableMovieList.ts
> +      page: 1,
А если у меня их больше чем на одну страницу?

2023-07-07 07:27 UTC, reshetov commented on src/api/graphql/hooks/queries/useGetFavoriteMovieList.ts
> +      page: 1,
см. комент выше

2023-07-07 07:27 UTC, reshetov commented on src/components/MovieAction/index.tsx
> +  const updateFavoriteMovie = async () => {
Тут слишком логика перекручена. Достаточно сделать метод
toggleFavoriteMovie который при вызове переключает состояние в обратное
Ну и для фронта написать setIsFavorite(!isFavorite) и все

2023-07-07 07:36 UTC, foxsheldin commented on src/api/graphql/hooks/queries/useGetAllAvailableMovieList.ts
> +      page: 1,
Это сделано для загрузки первой страницы. Обновление страниц у меня происходит здесь
https://github.com/foxsheldin/my-favorite-movies-front/pull/7/files#diff-9b1c3ee44cdb7e531e99ada8c219929583cf3d4c49e0fc0a86b1db29538ca887R42

2023-07-07 07:38 UTC, foxsheldin commented on src/api/graphql/hooks/queries/useGetFavoriteMovieList.ts
> +      page: 1,
Аналогично тому что выше
https://github.com/foxsheldin/my-favorite-movies-front/pull/7/files#diff-30d63bb9bbe75d70f4003e80a624eb82b83688ac7f56cccd249066013fb545e4R42

2023-07-10 06:27 UTC, reshetov approved these changes

2023-07-10 11:10 UTC, Isidora25 requested changes

2023-07-10 11:10 UTC, Isidora25 commented on src/components/NavBar/index.tsx
> +    localStorage.removeItem("access_token");
добавь тут еще очистку стора аполло https://www.apollographql.com/docs/react/networking/authentication/#reset-store-on-logout

2023-07-10 11:20 UTC, Isidora25 approved these changes

2023-07-11 09:20 UTC, merged